version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  to-do_list:
    build:
      context: .
    container_name: to-do_list
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/to-do_list
    volumes:
      - .:/usr/src/app
    command: npm run dev

volumes:
  mongo-data: